name = "example_lissome"
version = "0.1.0"
dependencies = { lustre = ">= 4.6.3 and < 5.0.0", gleam_stdlib = ">= 0.54.0 and < 1.0.0", plinth = ">= 0.5.6 and < 1.0.0", gleam_json = ">= 2.3.0 and < 3.0.0" }
